[package]
name = "neb"
version = "0.1.0"
authors = ["Jack Shi <shisoftgenius@gmail.com>"]

[lib]
name = "neb"

[[test]]
name = "tests"

[dependencies]
libc = "*"
log = "0.3"
lazy_static = "*"
uuid = { version = "0.2", features = ["v4", "v5"] }
chashmap = "*"
bifrost = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
bifrost_plugins = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
bifrost_hasher = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
serde = "1.0.4"
serde_derive = "1.0.4"
bincode = "0.8.0"
byteorder = "1"
parking_lot = {version = "0.3", features = ["nightly"]}
rand = "0.3"
futures = "0.1.9"
itertools = "0.6.0"
linked-hash-map = "0.4.2"

[dev-dependencies]
rand = "0.3"
env_logger = "0.3"
