[package]
name = "neb"
version = "0.1.0"
authors = ["Jack Shi <shisoftgenius@gmail.com>"]

[lib]
name = "neb"

[[test]]
name = "tests"

[dependencies]
libc = "*"
log = "0.3"
lazy_static = "*"
chashmap = "*"
bifrost = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
bifrost_plugins = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
bifrost_hasher = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
serde = "*"
serde_derive = "*"
bincode = "*"
byteorder = "1"
parking_lot = {version = "0.4", features = ["nightly"]}
rand = "0.3"
futures = "0.1.9"
itertools = "0.6.0"
linked-hash-map = "0.4.2"

[dev-dependencies]
rand = "0.3"
env_logger = "0.3"
