[package]
name = "neb"
version = "0.1.0"
authors = ["Hao Shi <shisoftgenius@gmail.com>"]

[lib]
name = "neb"

[[test]]
name = "tests"

[dependencies]
libc = "*"
log = "0.3"
lazy_static = "*"
bifrost = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
bifrost_plugins = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
bifrost_hasher = { git = "https://github.com/shisoft/bifrost", branch = "develop" }
dovahkiin = { git = "https://github.com/ShisoftResearch/Dovahkiin", branch = "develop" }
hermes = { git = "https://github.com/ShisoftResearch/Hermes.git" }
cuckoofilter = { git = "https://github.com/ShisoftResearch/rust-cuckoofilter.git" }
serde = "*"
serde_derive = "*"
bincode = "*"
byteorder = "1"
parking_lot = {version = "0.6", features = ["nightly", "deadlock_detection"]}
rand = "0.3"
linked-hash-map = "0.4"
bitflags = "1.0"
crc32c = "*"
itertools = "*"
smallvec = "*"
owning_ref = "0.3"
rayon = "1.0"

futures-await = "0.1"

num_cpus = "1.0"

[dev-dependencies]
rand = "0.3"
env_logger = "0.4"
serde_json = "1.0"