[package]
name = "neb"
version = "0.1.0"
authors = ["Jack Shi <shisoftgenius@gmail.com>"]

[lib]
name = "neb"

[[test]]
name = "tests"

[dependencies]
libc = "*"
log = "0.3"
lazy_static = "*"
uuid = { version = "0.2", features = ["v4", "v5"] }
twox-hash = "*"
concurrent-hashmap = "*"

[dev-dependencies]
rand = "0.3"
env_logger = "0.3"