[package]
name = "neb"
version = "0.1.0"
authors = ["Jack Shi <shisoftgenius@gmail.com>"]

[lib]
name = "neb"

[[test]]
name = "tests"

[dependencies]
libc = "0.2.16"
log = "0.3"
lazy_static = "*"
uuid = "0.2"

[dev-dependencies]
env_logger = "0.3"
